// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mail struct {
	Email string `json:"email"`
}

type Truck struct {
	ID      string `json:"id"`
	PlateNo string `json:"plateNo"`
}
